mod directed_dense_adjacency_matrix;
pub use directed_dense_adjacency_matrix::DirectedDenseAdjacencyMatrixGraph;

mod undirected_dense_adjacency_matrix;
pub use undirected_dense_adjacency_matrix::UndirectedDenseAdjacencyMatrixGraph;
