[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "causal-hub"
version = "0.0.6"
description = "A library for causal models, inference and discovery."
license = "AGPL-3.0-only"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Alessio Zanga", email = "alessio.zanga@outlook.it" }]
keywords = ["causality"]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "networkx>=3.4.2,<4.0.0",
    "numpy>=2.2.6,<3.0.0",
    "pandas>=3.0.0,<4.0.0",
    "polars>=1.40.1,<2.0.0",
    "scipy>=1.15.3,<2.0.0",
]

[dependency-groups]
dev = [
    "maturin>=1.13.1,<2.0.0",
    "patchelf>=0.17.2.4,<1.0.0 ; sys_platform != 'win32'",
    "pytest>=9.0.3,<10.0.0",
    "pydata-sphinx-theme>=0.16.0,<1.0.0",
    "sphinx>=9.1.0,<10.0.0",
]

[project.urls]
homepage = "https://github.com/AlessioZanga/causal-hub"
repository = "https://github.com/AlessioZanga/causal-hub"
documentation = "https://causal-hub.readthedocs.io/"

[tool.maturin]
features = ["pyo3/extension-module"]
manifest-path = "python/Cargo.toml"
python-source = "python"
