# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing

import causal_hub.datasets
import causal_hub.models

__all__ = [
    "FitMethod",
    "PK",
    "ParametersEstimator",
    "Scorer",
    "StructureEstimator",
    "cthc",
    "ctpc",
    "em",
    "hc",
    "sem",
]

@typing.final
class PK:
    r"""
    A struct representing prior knowledge.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        labels: typing.Any,
        forbidden: typing.Any,
        required: typing.Any,
        temporal_order: typing.Any,
    ) -> PK: ...

@typing.final
class FitMethod(enum.Enum):
    r"""
    Fitting methods for models: parameter fitting or structure learning.
    """

    Parameters = ...
    r"""
    Fit the model parameters given the structure.
    """
    Structure = ...
    r"""
    Learn the model structure from data, then fit the parameters.
    """

@typing.final
class ParametersEstimator(enum.Enum):
    r"""
    estimator methods.
    """

    MLE = ...
    r"""
    Maximum Likelihood Estimator.
    """
    BE = ...
    r"""
    Bayesian Estimator.
    """

@typing.final
class Scorer(enum.Enum):
    r"""
    Scoring criteria for score-based structure learning algorithms.
    """

    LL = ...
    r"""
    Log Likelihood (`LL`).
    """
    AIC = ...
    r"""
    Akaike Information Criterion (`AIC`).
    """
    AICC = ...
    r"""
    Akaike Information Criterion Corrected (`AICc`).
    """
    BIC = ...
    r"""
    Bayesian Information Criterion (`BIC`).
    """
    BICC = ...
    r"""
    Bayesian Information Criterion Corrected (`BICc`).
    """
    HQC = ...
    r"""
    Hannan-Quinn Criterion (`HQC`).
    """

@typing.final
class StructureEstimator(enum.Enum):
    r"""
    Structure estimator methods for score- and constraint-based structure
    learning algorithms.
    """

    CTHC = ...
    r"""
    Continuous Time Hill Climbing (`CTHC`).
    """
    CTPC = ...
    r"""
    Continuous Time Peter-Clark (`CTPC`).
    """

def cthc(
    trajectories: datasets.CatTrjs, scorer: Scorer = Scorer.BIC, **kwargs: typing.Any
) -> models.CatCTBN:
    r"""
    Perform structure learning using the Continuous Time Hill Climbing (CTHC) algorithm.

    CTHC learns the structure of a Continuous Time Bayesian Network (CTBN)
    from trajectories. It explores the space of directed graphs greedily: at
    each iteration it evaluates all single-edge additions, deletions and
    reversals, and applies the move that most increases the score of the
    model until no improving move is found.

    Parameters
    ----------
    trajectories: CatTrjs
        The trajectories to learn the structure from.
    scorer: Scorer | None
        The scoring criterion to maximize, one of `Scorer.{LL, AIC,
        AICC, BIC, BICC, HQC}` (default is `Scorer.BIC`).
    **kwargs: dict | None
        Optional keyword arguments:

    - `parameters_estimator`: The parameter estimator used to fit the local
      models, either `ParametersEstimator.MLE` or `ParametersEstimator.BE`
      (default is `ParametersEstimator.BE`).
    - `initial_graph`: The initial graph (`DiGraph`) to start the search
      from (default is an empty graph). Its labels must match the
      trajectories.
    - `max_parents`: The maximum number of parents for each vertex
      (default is no limit).
    - `missing_method`: The method (`MissingMethod`) used to handle missing
      data, one of `MissingMethod.{LW, PW, IPW, AIPW}` (default is `None`).
    - `missing_mechanism`: The missing data mechanism (`MissingMechanism`)
      associated to the trajectories (default is `None`). It is required by
      `MissingMethod.IPW` and `MissingMethod.AIPW`, and it must be `None`
      otherwise.
    - `parallel`: Whether to run the algorithm in parallel (default is `True`).
    - `prior_knowledge`: The prior knowledge (`PK`) constraining the search,
      e.g., forbidden and required edges or temporal tiers
      (default is `None`).

    Returns
    -------
    CatCTBN
        The fitted model over the learned structure.
    """

def ctpc(
    trajectories: datasets.CatTrjs,
    f_test: builtins.float = 0.01,
    c_test: builtins.float = 0.01,
    **kwargs: typing.Any,
) -> models.CatCTBN:
    r"""
    Perform structure learning using the Continuous Time Peter-Clark (CTPC) algorithm.

    CTPC learns the structure of a Continuous Time Bayesian Network (CTBN)
    from trajectories. It is a constraint-based algorithm: it starts from a
    complete graph and removes edges whose end-points are conditionally
    independent given suitable separating sets, as assessed by the
    significance tests below.

    Parameters
    ----------
    trajectories: CatTrjs
        The trajectories to learn the structure from.
    f_test: float | None
        The significance level of the F-test for the transition rates
        (default is `0.01`). It must be in `[0, 1]`.
    c_test: float | None
        The significance level of the chi-squared test for the initial
        distributions (default is `0.01`). It must be in `[0, 1]`.
    **kwargs: dict | None
        Optional keyword arguments:

    - `parameters_estimator`: The parameter estimator used to fit the local
      models, either `ParametersEstimator.MLE` or `ParametersEstimator.BE`
      (default is `ParametersEstimator.BE`).
    - `initial_graph`: The initial graph (`DiGraph`) to start the search
      from (default is a complete graph). Its labels must match the
      trajectories.
    - `missing_method`: The method (`MissingMethod`) used to handle missing
      data, one of `MissingMethod.{LW, PW, IPW, AIPW}` (default is `None`).
    - `missing_mechanism`: The missing data mechanism (`MissingMechanism`)
      associated to the trajectories (default is `None`). It is required by
      `MissingMethod.IPW` and `MissingMethod.AIPW`, and it must be `None`
      otherwise.
    - `parallel`: Whether to run the algorithm in parallel (default is `True`).
    - `prior_knowledge`: The prior knowledge (`PK`) constraining the search,
      e.g., forbidden and required edges or temporal tiers
      (default is `None`).

    Returns
    -------
    CatCTBN
        The fitted model over the learned structure.
    """

def em(
    evidence: datasets.CatTrjsEv,
    graph: models.DiGraph,
    max_iter: builtins.int = 10,
    **kwargs: typing.Any,
) -> dict:
    r"""
    A function to perform parameter learning using the Expectation Maximization (EM) algorithm.

    **kwargs: dict | None
        Optional keyword arguments:

    - `seed`: The seed of the random number generator (default is `42`).
    """

def hc(
    dataset: datasets.Dataset, scorer: Scorer = Scorer.BIC, **kwargs: typing.Any
) -> typing.Union[models.CatBN, models.GaussBN]:
    r"""
    Perform structure learning using the Hill Climbing (HC) algorithm.

    HC explores the space of directed acyclic graphs (DAGs) greedily: at each
    iteration it evaluates all single-edge additions, deletions and reversals,
    and applies the move that most increases the score of the model until no
    improving move is found.

    Parameters
    ----------
    dataset: CatTable | CatIncTable | CatWtdTable | GaussTable | GaussIncTable | GaussWtdTable
        The dataset to learn the structure from.
    scorer: Scorer | None
        The scoring criterion to maximize, one of `Scorer.{LL, AIC,
        AICC, BIC, BICC, HQC}` (default is `Scorer.BIC`).
    **kwargs: dict | None
        Optional keyword arguments:

    - `parameters_estimator`: The parameter estimator used to fit the local
      models, either `ParametersEstimator.MLE` or `ParametersEstimator.BE`
      (default is `ParametersEstimator.BE`).
    - `initial_graph`: The initial graph (`DiGraph`) to start the search
      from (default is an empty graph). Its labels must match the dataset.
    - `max_parents`: The maximum number of parents for each vertex
      (default is no limit).
    - `max_iter`: The maximum number of iterations of the search
      (default is unlimited).
    - `missing_method`: The method (`MissingMethod`) used to handle missing
      data, one of `MissingMethod.{LW, PW, IPW, AIPW}` (default is `None`).
    - `missing_mechanism`: The missing data mechanism (`MissingMechanism`)
      associated to the dataset (default is `None`). It is required by
      `MissingMethod.IPW` and `MissingMethod.AIPW`, and it must be `None`
      otherwise.
    - `parallel`: Whether to run the algorithm in parallel (default is `True`).
    - `prior_knowledge`: The prior knowledge (`PK`) constraining the search,
      e.g., forbidden and required edges or temporal tiers
      (default is `None`).

    Returns
    -------
    CatBN | GaussBN
        The fitted model over the learned structure: `CatBN` for categorical
        datasets, `GaussBN` for Gaussian ones.
    """

def sem(
    evidence: datasets.CatTrjsEv,
    structure_estimator: StructureEstimator = StructureEstimator.CTHC,
    max_iter: builtins.int = 10,
    f_test: builtins.float = 0.01,
    c_test: builtins.float = 0.01,
    **kwargs: typing.Any,
) -> dict:
    r"""
    A function to perform structure learning using the Structural Expectation Maximization (SEM) algorithm.

    Parameters
    ----------
    evidence: CatTrjsEv
        The evidence to learn the structure from.
    structure_estimator: StructureEstimator | None
        The structure learning algorithm to use, one of
        `StructureEstimator.{CTHC, CTPC}` (default is
        `StructureEstimator.CTHC`).

    **kwargs: dict | None
        Optional keyword arguments:

    - `parallel`: Whether to run the algorithm in parallel (default is `True`).
    - `seed`: The seed of the random number generator (default is `42`).
    """
