# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing

import causal_hub.datasets
import causal_hub.models

__all__ = [
    "EstimatorMethod",
    "PK",
    "em",
    "sem",
]

@typing.final
class PK:
    r"""
    A struct representing prior knowledge.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        labels: typing.Any,
        forbidden: typing.Any,
        required: typing.Any,
        temporal_order: typing.Any,
    ) -> PK: ...

@typing.final
class EstimatorMethod(enum.Enum):
    r"""
    estimator methods.
    """

    MLE = ...
    r"""
    Maximum Likelihood Estimator.
    """
    BE = ...
    r"""
    Bayesian Estimator.
    """

def em(
    evidence: datasets.CatTrjsEv,
    graph: models.DiGraph,
    max_iter: builtins.int = 10,
    seed: builtins.int = 42,
) -> dict:
    r"""
    A function to perform parameter learning using the Expectation Maximization (EM) algorithm.
    """

def sem(
    evidence: datasets.CatTrjsEv,
    prior_knowledge: PK,
    algorithm: builtins.str,
    max_iter: builtins.int = 10,
    seed: builtins.int = 42,
    **kwargs: typing.Any,
) -> dict:
    r"""
    A function to perform structure learning using the Structural Expectation Maximization (SEM) algorithm.
    """
