# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

import causal_hub.datasets
import causal_hub.estimators
import numpy
import numpy.typing

__all__ = [
    "CatBN",
    "CatCIM",
    "CatCPD",
    "CatCTBN",
    "CatPhi",
    "DiGraph",
    "GaussBN",
    "GaussCPD",
    "GaussPhi",
    "MixedBN",
    "MixedCPD",
    "MixedPhi",
    "UnGraph",
]

@typing.final
class CatBN:
    r"""
    A categorical Bayesian network (BN).
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, graph: DiGraph, cpds: typing.Any) -> CatBN:
        r"""
        Constructs a new Bayesian network.

        Parameters
        ----------
        graph: DiGraph
            The underlying graph.
        cpds: Iterable[CatCPD]
            The conditional probability distributions.

        Returns
        -------
        CatBN
            A new Bayesian network instance.
        """

    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the name of the model, if any.

        Returns
        -------
        str | None
            The name of the model, if it exists.
        """

    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the description of the model, if any.

        Returns
        -------
        str | None
            The description of the model, if it exists.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the variables.

        Returns
        -------
        list[str]
            A reference to the labels.
        """

    def graph(self) -> DiGraph:
        r"""
        Returns the underlying graph.

        Returns
        -------
        DiGraph
            A reference to the graph.
        """

    def cpds(self) -> builtins.dict[builtins.str, CatCPD]:
        r"""
        Returns the a map labels-distributions.

        Returns
        -------
        dict[str, CatCPD]
            A reference to the CPDs.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    def support(self) -> builtins.dict[builtins.str, builtins.list[builtins.str]]:
        r"""
        Returns the support (states) of the model variables.

        Returns
        -------
        dict[str, list[str]]
            A mapping from each variable to its possible states.
        """

    def select(self, x: typing.Any) -> CatBN:
        r"""
        Restrict the model to the specified variables.

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables to select.

        Returns
        -------
        CatBN
            A model restricted to the specified variables.
        """

    def topological_order(self) -> builtins.list[builtins.str]:
        r"""
        Returns the topological order of the underlying graph.

        Returns
        -------
        list[str]
            A topological ordering of the variables.
        """

    @classmethod
    def fit(
        cls,
        dataset: datasets.Dataset,
        graph: DiGraph,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        parallel: builtins.bool = True,
        **kwargs: typing.Any,
    ) -> CatBN:
        r"""
        Fit the model to a dataset and a given graph.

        Parameters
        ----------
        dataset: CatTable | CatIncTable
            The dataset to fit the model to.
        graph: DiGraph
            The graph to fit the model to.
        estimator: EstimatorMethod | None
            The estimator to use for fitting (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        parallel: bool
            The flag to enable parallel fitting (default is `true`).
        **kwargs: dict | None
            Optional keyword arguments:

        - `alpha`: The prior of the Bayesian estimator (float64).

        Returns
        -------
        CatBN
            A new fitted model.
        """

    def sample(
        self, n: builtins.int, seed: builtins.int = 31, parallel: builtins.bool = True
    ) -> datasets.CatTable:
        r"""
        Generate samples from the model.

        Parameters
        ----------
        n: int
            The number of samples to generate.
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel sampling (default is `true`).

        Returns
        -------
        CatTable
            A new dataset containing the samples.
        """

    def estimate(
        self,
        x: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        seed: builtins.int = 31,
        parallel: builtins.bool = True,
    ) -> CatCPD:
        r"""
        Estimate a conditional probability distribution (CPD).

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables.
        z: str | Iterable[str]
            A conditioning variable or an iterable of conditioning variables.
        w: CatEv | dict[str, str] | None
            Optional evidence to condition on during inference.
        estimator: EstimatorMethod | None
            The estimator to use for estimation (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel estimation (default is `true`).

        Returns
        -------
        CatCPD
            A new conditional probability distribution.
        """

    def do_estimate(
        self,
        x: typing.Any,
        y: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        seed: builtins.int = 31,
        parallel: builtins.bool = True,
    ) -> typing.Optional[CatCPD]:
        r"""
        Estimate a conditional population average causal effect (CPACE).

        Parameters
        ----------
        x: str | Iterable[str]
            An intervention variable or an iterable of intervention variables.
        y: str | Iterable[str]
            An outcome variable or an iterable of outcome variables.
        z: str | Iterable[str]
            A conditioning variable or an iterable of conditioning variables.
        w: CatEv | dict[str, str] | None
            Optional evidence to condition on during inference.
        estimator: EstimatorMethod | None
            The estimator to use for estimation (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel estimation (default is `true`).

        Returns
        -------
        CatCPD | None
            A new conditional population average causal effect (CPACE) distribution, if identifiable.
        """

    @classmethod
    def random(
        cls,
        states: dict,
        alpha: builtins.float = 1.0,
        p: builtins.float = 0.1,
        seed: builtins.int = 31,
    ) -> CatBN:
        r"""
        Generates a random categorical Bayesian network.

        Parameters
        ----------
        states: dict[str, tuple[str, ...]]
            The states of the variables.
        alpha: float, default=1.0
            The parameter of the Dirichlet distribution.
        p: float, default=0.1
            The probability of generating an edge.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        CatBN
            A random categorical Bayesian network.
        """

    @classmethod
    def from_bif_string(cls, bif: builtins.str) -> CatBN:
        r"""
        Read class from a BIF string.

        Parameters
        ----------
        bif: str
            The BIF string to read from.

        Returns
        -------
        CatBN
            A new Bayesian network instance.
        """

    def to_bif_string(self) -> builtins.str:
        r"""
        Write class to a BIF string.

        Returns
        -------
        str
            A BIF string representation of the model.
        """

    @classmethod
    def from_bif_file(cls, path: builtins.str) -> CatBN:
        r"""
        Read class from a BIF file.

        Parameters
        ----------
        path: str
            The path to the BIF file to read from.

        Returns
        -------
        CatBN
            A new Bayesian network instance.
        """

    def to_bif_file(self, path: builtins.str) -> None:
        r"""
        Write class to a BIF file.

        Parameters
        ----------
        path: str
            The path to the BIF file to write to.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> CatBN:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        CatBN
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> CatBN:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        CatBN
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class CatCIM:
    r"""
    A struct representing a categorical conditional intensity matrix (CIM).
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the label of the conditioned variable.

        Returns
        -------
        list[str]
            A reference to the label.
        """

    def support(self) -> builtins.dict[builtins.str, tuple]:
        r"""
        Returns the support of the conditioned variable.

        Returns
        -------
        dict[str, tuple[str]]
            A reference to the support.
        """

    def shape(self) -> builtins.list[builtins.int]:
        r"""
        Returns the shape of the conditioned variable.

        Returns
        -------
        list[int]
            The shape of the conditioned variable.
        """

    def conditioning_labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the conditioned variables.

        Returns
        -------
        list[str]
            A reference to the conditioning labels.
        """

    def conditioning_support(self) -> builtins.dict[builtins.str, tuple]:
        r"""
        Returns the support of the conditioning variables.

        Returns
        -------
        dict[str, tuple[str]]
            The support of the conditioning variables.
        """

    def conditioning_shape(self) -> builtins.list[builtins.int]:
        r"""
        Returns the shape of the conditioning variables.

        Returns
        -------
        list[int]
            The shape of the conditioning variables.
        """

    def parameters(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Returns the parameters.

        Returns
        -------
        numpy.ndarray
            A reference to the parameters.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    def fitted_statistics(self) -> typing.Optional[dict]:
        r"""
        Returns the fitted statistics used to fit the distribution, if any.

        Returns
        -------
        dict[str, ...] | None
            A dictionary containing the fitted statistics used to fit the distribution, if any.
        """

    def fitted_log_likelihood(self) -> typing.Optional[builtins.float]:
        r"""
        Returns the log-likelihood given the distribution, if any.

        Returns
        -------
        float | None
            The log-likelihood given the distribution, if any.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> CatCIM:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        CatCIM
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> CatCIM:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        CatCIM
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class CatCPD:
    r"""
    A struct representing a categorical conditional probability distribution.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the label of the conditioned variable.

        Returns
        -------
        list[str]
            A reference to the label.
        """

    def support(self) -> builtins.dict[builtins.str, tuple]:
        r"""
        Returns the states of the conditioned variable.

        Returns
        -------
        dict[str, tuple[str, ...]]
            The states of the conditioned variable.
        """

    def shape(self) -> builtins.list[builtins.int]:
        r"""
        Returns the shape of the conditioned variable.

        Returns
        -------
        list[int]
            The shape of the conditioned variable.
        """

    def conditioning_labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the conditioned variables.

        Returns
        -------
        list[str]
            A reference to the conditioning labels.
        """

    def conditioning_support(self) -> builtins.dict[builtins.str, tuple]:
        r"""
        Returns the states of the conditioning variables.

        Returns
        -------
        dict[str, tuple[str, ...]]
            The states of the conditioning variables.
        """

    def conditioning_shape(self) -> builtins.list[builtins.int]:
        r"""
        Returns the shape of the conditioning variables.

        Returns
        -------
        list[int]
            The shape of the conditioning variables.
        """

    def parameters(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Returns the parameters.

        Returns
        -------
        numpy.ndarray
            A reference to the parameters.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    def fitted_statistics(self) -> typing.Optional[dict]:
        r"""
        Returns the fitted statistics used to fit the distribution, if any.

        Returns
        -------
        dict[str, ...] | None
            A dictionary containing the fitted statistics used to fit the distribution, if any.
        """

    def fitted_log_likelihood(self) -> typing.Optional[builtins.float]:
        r"""
        Returns the log-likelihood given the distribution, if any.

        Returns
        -------
        float | None
            The log-likelihood given the distribution, if any.
        """

    def __repr__(self) -> builtins.str:
        r"""
        Returns the string representation of the CatCPD.
        """

    @classmethod
    def random(
        cls,
        states: dict,
        conditioning_support: dict,
        alpha: builtins.float = 1.0,
        seed: builtins.int = 31,
    ) -> CatCPD:
        r"""
        Generates a random categorical conditional probability distribution.

        Parameters
        ----------
        states: dict[str, tuple[str, ...]]
            The states of the variable.
        conditioning_support: dict[str, tuple[str, ...]]
            The support of the conditioning variables.
        alpha: float, default=1.0
            The parameter of the Dirichlet distribution.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        CatCPD
            A random categorical conditional probability distribution.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> CatCPD:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        CatCPD
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> CatCPD:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        CatCPD
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class CatCTBN:
    r"""
    A continuous-time Bayesian network (CTBN).
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, graph: DiGraph, cims: typing.Any) -> CatCTBN:
        r"""
        Constructs a new continuous-time Bayesian network.

        Parameters
        ----------
        graph: DiGraph
            The underlying graph.
        cims: Iterable[CatCIM]
            The conditional intensity matrices.

        Returns
        -------
        CatCTBN
            A new continuous-time Bayesian network instance.
        """

    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the name of the model, if any.

        Returns
        -------
        str | None
            The name of the model, if it exists.
        """

    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the description of the model, if any.

        Returns
        -------
        str | None
            The description of the model, if it exists.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the variables.

        Returns
        -------
        list[str]
            A reference to the labels.
        """

    def initial_distribution(self) -> CatBN:
        r"""
        Returns the initial distribution.

        Returns
        -------
        CatBN
            A reference to the initial distribution.
        """

    def graph(self) -> DiGraph:
        r"""
        Returns the underlying graph.

        Returns
        -------
        DiGraph
            A reference to the graph.
        """

    def cims(self) -> builtins.dict[builtins.str, CatCIM]:
        r"""
        Returns the a map labels-distributions.

        Returns
        -------
        dict[str, CatCIM]
            A reference to the CIMs.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    @classmethod
    def fit(
        cls,
        dataset: datasets.CatTrjs,
        graph: DiGraph,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        parallel: builtins.bool = True,
        **kwargs: typing.Any,
    ) -> CatCTBN:
        r"""
        Fit the model to a dataset and a given graph.

        Parameters
        ----------
        dataset: CatTrjs
            The dataset to fit the model to.
        graph: DiGraph
            The graph to fit the model to.
        estimator: EstimatorMethod | None
            The estimator to use for fitting (default is `EstimatorMethod.MLE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        parallel: bool
            The flag to enable parallel fitting (default is `true`).
        **kwargs: dict | None
            Optional keyword arguments:

        - `alpha`: The prior of the Bayesian estimator (int, float64).

        Returns
        -------
        CatCTBN
            A new fitted model.
        """

    def sample(
        self,
        n: builtins.int,
        max_len: typing.Optional[builtins.int] = None,
        max_time: typing.Optional[builtins.float] = None,
        seed: builtins.int = 31,
        parallel: builtins.bool = True,
    ) -> datasets.CatTrjs:
        r"""
        Sample from the model.

        Parameters
        ----------
        n: int
            The number of trajectories to sample.
        max_len: int | None
            The maximum length of each trajectory (default is `None`).
            Must be set if `max_time` is `None`.
        max_time: float | None
            The maximum time of each trajectory (default is `None`).
            Must be set if `max_len` is `None`.
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel sampling (default is `true`).

        Returns
        -------
        CatTrjs
            A new dataset containing the sampled trajectories.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> CatCTBN:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        CatCTBN
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> CatCTBN:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        CatCTBN
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class CatPhi:
    r"""
    A struct representing a categorical potential.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the potential.
        """

    def support(self) -> builtins.dict[builtins.str, tuple]:
        r"""
        Returns the support of the potential.
        """

    def shape(self) -> builtins.list[builtins.int]:
        r"""
        Returns the shape of the potential.
        """

    def parameters(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Returns the parameters.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.
        """

    def condition(self, evidence: typing.Any) -> CatPhi:
        r"""
        Conditions the potential on observed evidence.
        """

    def marginalize(self, x: typing.Any) -> CatPhi:
        r"""
        Marginalizes the potential over a set of variables.
        """

    def normalize(self) -> CatPhi:
        r"""
        Normalizes the potential so its entries sum to one.
        """

    @classmethod
    def from_cpd(cls, cpd: CatCPD) -> CatPhi:
        r"""
        Converts a CatCPD to a CatPhi.
        """

    def into_cpd(self, x: typing.Any, z: typing.Any) -> CatCPD:
        r"""
        Converts the potential to a CatCPD.
        """

    def __repr__(self) -> builtins.str:
        r"""
        Returns the string representation of the CatPhi.
        """

    def __mul__(self, other: CatPhi) -> CatPhi:
        r"""
        Multiplies two potentials.
        """

    def __imul__(self, other: CatPhi) -> None:
        r"""
        In-place multiplication of two potentials.
        """

    def __truediv__(self, other: CatPhi) -> CatPhi:
        r"""
        Divides two potentials.
        """

    def __idiv__(self, other: CatPhi) -> None:
        r"""
        In-place division of two potentials.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> CatPhi:
        r"""
        Read instance from a JSON string.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> CatPhi:
        r"""
        Read instance from a JSON file.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.
        """

@typing.final
class DiGraph:
    r"""
    A struct representing a directed graph using an adjacency matrix.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    @classmethod
    def empty(cls, vertices: typing.Any) -> DiGraph:
        r"""
        Creates an empty directed graph with the given vertices.

        Parameters
        ----------
        vertices: Iterable[str]
            The vertices of the graph.
            Vertices will be sorted in alphabetical order.

        Returns
        -------
        DiGraph
            A new graph instance.
        """

    @classmethod
    def complete(cls, vertices: typing.Any) -> DiGraph:
        r"""
        Creates a complete directed graph with the given vertices.

        Parameters
        ----------
        vertices: Iterable[str]
            The the vertices of the graph.
            Vertices will be sorted in alphabetical order.
            No self-loops are created.

        Returns
        -------
        DiGraph
            A new graph instance.
        """

    def vertices(self) -> builtins.list[builtins.str]:
        r"""
        Returns the vertices of the graph.

        # Returns

        A list of vertices.
        """

    def has_vertex(self, x: builtins.str) -> builtins.bool:
        r"""
        Checks if a vertex exists in the graph.

        Parameters
        ----------
        x: str
            The vertex.

        Returns
        -------
        bool
            `true` if the vertex exists, `false` otherwise.
        """

    def add_vertex(self, x: builtins.str) -> builtins.int:
        r"""
        Adds a new vertex with the given label to the graph.

        Parameters
        ----------
        x: str
            The label of the vertex to add.

        Returns
        -------
        int
            The index of the (possibly new) vertex.
            Vertices are kept sorted in alphabetical order:
            adding a vertex may shift the indices of other vertices.
        """

    def del_vertex(self, x: builtins.str) -> builtins.bool:
        r"""
        Deletes the vertex with the given label from the graph,
        together with all its incident edges.

        Parameters
        ----------
        x: str
            The label of the vertex to delete.

        Returns
        -------
        bool
            `true` if the vertex was deleted, `false` if it did not exist.
            Vertices are kept sorted in alphabetical order:
            deleting a vertex may shift the indices of other vertices.
        """

    def edges(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        Returns the edges of the graph.

        Returns
        -------
        list[tuple[str, str]]
            A list of edges.
        """

    def has_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Checks if there is an edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if there is an edge between `x` and `y`, `false` otherwise.
        """

    def add_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Adds an edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if the edge was added, `false` if it already existed.
        """

    def del_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Deletes the edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if the edge was deleted, `false` if it did not exist.
        """

    def parents(self, x: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Returns the parents of a vertex `x`.

        Parameters
        ----------
        x: str | Iterable[str]
            A vertex or an iterable of vertices.

        Returns
        -------
        list[str]
            A list of parent vertices.
        """

    def ancestors(self, x: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Returns the ancestors of a vertex `x`.

        Parameters
        ----------
        x: str | Iterable[str]
            A vertex or an iterable of vertices.

        Returns
        -------
        list[str]
            A list of ancestor vertices.
        """

    def children(self, x: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Returns the children of a vertex `x`.

        Parameters
        ----------
        x: str | Iterable[str]
            A vertex or an iterable of vertices.

        Returns
        -------
        list[str]
            A list of child vertices.
        """

    def descendants(self, x: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Returns the descendants of a vertex `x`.

        Parameters
        ----------
        x: str | Iterable[str]
            A vertex or an iterable of vertices.

        Returns
        -------
        list[str]
            A list of descendant vertices.
        """

    def is_separator_set(
        self, x: typing.Any, y: typing.Any, z: typing.Any
    ) -> builtins.bool:
        r"""
        Checks if the vertex set `Z` is a separator set for `X` and `Y`.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        z: Iterable[str]
            An iterable of vertices representing set `Z`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, or `Z` are out of bounds.
        * `X`, `Y` or `Z` are not disjoint sets.
        * `X` and `Y` are empty sets.

        Returns
        -------
        bool
            `true` if `X` and `Y` are separated by `Z`, `false` otherwise.
        """

    def is_minimal_separator_set(
        self,
        x: typing.Any,
        y: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        v: typing.Optional[typing.Any] = None,
    ) -> builtins.bool:
        r"""
        Checks if the vertex set `Z` is a minimal separator set for `X` and `Y`.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        z: Iterable[str]
            An iterable of vertices representing set `Z`.
        w: Iterable[str] | None
            An optional iterable of vertices representing set `W`.
        v: Iterable[str] | None
            An optional iterable of vertices representing set `V`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, `Z`, `W` or `V` are out of bounds.
        * `X`, `Y` or `Z` are not disjoint sets.
        * `X` and `Y` are empty sets.
        * Not `W` <= `Z` <= `V`.

        Returns
        -------
        bool
            `true` if `Z` is a minimal separator set for `X` and `Y`, `false` otherwise.
        """

    def find_minimal_separator_set(
        self,
        x: typing.Any,
        y: typing.Any,
        w: typing.Optional[typing.Any] = None,
        v: typing.Optional[typing.Any] = None,
    ) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Finds a minimal separator set for the vertex sets `X` and `Y`, if any.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        w: Iterable[str] | None
            An optional iterable of vertices representing set `W`.
        v: Iterable[str] | None
            An optional iterable of vertices representing set `V`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, `W` or `V` are out of bounds.
        * `X` and `Y` are not disjoint sets.
        * `X` or `Y` are empty sets.
        * Not `W` <= `V`.

        Returns
        -------
        list[str] | None
            A minimal separator set, or `None` if no separator set exists.
        """

    def is_backdoor_set(
        self, x: typing.Any, y: typing.Any, z: typing.Any
    ) -> builtins.bool:
        r"""
        Checks if the vertex set `Z` is a backdoor set for `X` and `Y`.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        z: Iterable[str]
            An iterable of vertices representing set `Z`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, or `Z` are out of bounds.
        * `X`, `Y` or `Z` are not disjoint sets.
        * `X` and `Y` are empty sets.

        Returns
        -------
        bool
            `true` if `Z` is a backdoor set for `X` and `Y`, `false` otherwise.
        """

    def is_minimal_backdoor_set(
        self,
        x: typing.Any,
        y: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        v: typing.Optional[typing.Any] = None,
    ) -> builtins.bool:
        r"""
        Checks if the vertex set `Z` is a minimal backdoor set for `X` and `Y`.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        z: Iterable[str]
            An iterable of vertices representing set `Z`.
        w: Iterable[str] | None
            An optional iterable of vertices representing set `W`.
        v: Iterable[str] | None
            An optional iterable of vertices representing set `V`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, `Z`, `W` or `V` are out of bounds.
        * `X`, `Y` or `Z` are not disjoint sets.
        * `X` and `Y` are empty sets.
        * Not `W` <= `Z` <= `V`.

        Returns
        -------
        bool
            `true` if `Z` is a minimal backdoor set for `X` and `Y`, `false` otherwise.
        """

    def find_minimal_backdoor_set(
        self,
        x: typing.Any,
        y: typing.Any,
        w: typing.Optional[typing.Any] = None,
        v: typing.Optional[typing.Any] = None,
    ) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Finds a minimal backdoor set for the vertex sets `X` and `Y`, if any.

        Parameters
        ----------
        x: Iterable[str]
            An iterable of vertices representing set `X`.
        y: Iterable[str]
            An iterable of vertices representing set `Y`.
        w: Iterable[str] | None
            An optional iterable of vertices representing set `W`.
        v: Iterable[str] | None
            An optional iterable of vertices representing set `V`.

        Raises
        ------
        ValueError
            Raised if:

        * Any of the vertex in `X`, `Y`, `W` or `V` are out of bounds.
        * `X` and `Y` are not disjoint sets.
        * `X` or `Y` are empty sets.
        * Not `W` <= `V`.

        Returns
        -------
        list[str] | None
            A minimal backdoor set, or `None` if no backdoor set exists.
        """

    @classmethod
    def random(
        cls, labels: typing.Any, p: builtins.float = 0.1, seed: builtins.int = 31
    ) -> DiGraph:
        r"""
        Generates a random directed graph.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the graph.
        p: float, default=0.1
            The probability of generating an edge.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        DiGraph
            A random directed graph.
        """

    @classmethod
    def random_dag(
        cls, vertices: typing.Any, p: builtins.float = 0.1, seed: builtins.int = 31
    ) -> DiGraph:
        r"""
        Generates a random directed acyclic graph.

        Parameters
        ----------
        vertices: Iterable[str]
            The vertices of the graph.
        p: float, default=0.1
            The probability of generating an edge.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        DiGraph
            A random directed acyclic graph.
        """

    @classmethod
    def from_networkx(cls, g: typing.Any) -> DiGraph:
        r"""
        Converts from a NetworkX DiGraph.

        Parameters
        ----------
        g: networkx.DiGraph
            A NetworkX DiGraph to convert from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_networkx(self) -> typing.Any:
        r"""
        Converts to a NetworkX DiGraph.

        Returns
        -------
        networkx.DiGraph
            A NetworkX DiGraph representation of the graph.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> DiGraph:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> DiGraph:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

    def select(self, x: typing.Any) -> DiGraph:
        r"""
        Restrict the graph to the specified variables.

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables to select.

        Returns
        -------
        DiGraph
            A graph restricted to the specified variables.
        """

    def topological_order(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Returns a topological order of the graph, if it is a DAG.

        Returns
        -------
        list[str] | None
            A topological ordering of the vertices, or `None` if the graph is
            not a directed acyclic graph.
        """

    @classmethod
    def from_adjacency_matrix(
        cls, labels: typing.Any, adjacency_matrix: typing.Any
    ) -> DiGraph:
        r"""
        Creates a directed graph from an adjacency matrix and labels.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the vertices.
        adjacency_matrix: numpy.ndarray
            A 2D boolean array representing the adjacency matrix.

        Returns
        -------
        DiGraph
            A new graph instance.
        """

    def to_adjacency_matrix(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Converts the graph to an adjacency matrix.

        Returns
        -------
        numpy.ndarray
            A 2D boolean array representing the adjacency matrix.
        """

    @classmethod
    def from_dot_string(cls, dot: builtins.str) -> DiGraph:
        r"""
        Read instance from a DOT string.

        Parameters
        ----------
        dot: str
            The DOT string to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_dot_string(self) -> builtins.str:
        r"""
        Write instance to a DOT string.

        Returns
        -------
        str
            A DOT string representation of the instance.
        """

    @classmethod
    def from_dot_file(cls, path: builtins.str) -> DiGraph:
        r"""
        Read instance from a DOT file.

        Parameters
        ----------
        path: str
            The path to the DOT file to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_dot_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a DOT file.

        Parameters
        ----------
        path: str
            The path to the DOT file to write to.
        """

    @classmethod
    def from_gml_string(cls, gml: builtins.str) -> DiGraph:
        r"""
        Read instance from a GML string.

        Parameters
        ----------
        gml: str
            The GML string to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_gml_string(self) -> builtins.str:
        r"""
        Write instance to a GML string.

        Returns
        -------
        str
            A GML string representation of the instance.
        """

    @classmethod
    def from_gml_file(cls, path: builtins.str) -> DiGraph:
        r"""
        Read instance from a GML file.

        Parameters
        ----------
        path: str
            The path to the GML file to read from.

        Returns
        -------
        DiGraph
            A new instance.
        """

    def to_gml_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a GML file.

        Parameters
        ----------
        path: str
            The path to the GML file to write to.
        """

@typing.final
class GaussBN:
    r"""
    A Gaussian Bayesian network.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, graph: DiGraph, cpds: typing.Any) -> GaussBN:
        r"""
        Constructs a new Bayesian network.

        Parameters
        ----------
        graph: DiGraph
            The underlying graph.
        cpds: Iterable[GaussCPD]
            The conditional probability distributions.

        Returns
        -------
        GaussBN
            A new Bayesian network instance.
        """

    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the name of the model, if any.

        Returns
        -------
        str | None
            The name of the model, if it exists.
        """

    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the description of the model, if any.

        Returns
        -------
        str | None
            The description of the model, if it exists.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the variables.

        Returns
        -------
        list[str]
            A reference to the labels.
        """

    def graph(self) -> DiGraph:
        r"""
        Returns the underlying graph.

        Returns
        -------
        DiGraph
            A reference to the graph.
        """

    def cpds(self) -> builtins.dict[builtins.str, GaussCPD]:
        r"""
        Returns the a map labels-distributions.

        Returns
        -------
        dict[str, GaussCPD]
            A reference to the CPDs.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    def support(
        self,
    ) -> builtins.dict[builtins.str, tuple[builtins.float, builtins.float]]:
        r"""
        Returns the support (ranges) of the model variables.

        Returns
        -------
        dict[str, tuple[float, float]]
            A mapping from each variable to its (low, high) range.
        """

    def select(self, x: typing.Any) -> GaussBN:
        r"""
        Restrict the model to the specified variables.

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables to select.

        Returns
        -------
        GaussBN
            A model restricted to the specified variables.
        """

    def topological_order(self) -> builtins.list[builtins.str]:
        r"""
        Returns the topological order of the underlying graph.

        Returns
        -------
        list[str]
            A topological ordering of the variables.
        """

    @classmethod
    def fit(
        cls,
        dataset: datasets.Dataset,
        graph: DiGraph,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        parallel: builtins.bool = True,
        **kwargs: typing.Any,
    ) -> GaussBN:
        r"""
        Fit the model to a dataset and a given graph.

        Parameters
        ----------
        dataset: GaussTable
            The dataset to fit the model to.
        graph: DiGraph
            The graph to fit the model to.
        estimator: EstimatorMethod | None
            The estimator to use for fitting (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        parallel: bool
            The flag to enable parallel fitting (default is `true`).
        **kwargs: dict | None
            Optional keyword arguments:

        - `alpha`: The prior of the Bayesian estimator (float64).

        Returns
        -------
        GaussBN
            A new fitted model.
        """

    def sample(
        self, n: builtins.int, seed: builtins.int = 31, parallel: builtins.bool = True
    ) -> datasets.GaussTable:
        r"""
        Generate samples from the model.

        Parameters
        ----------
        n: int
            The number of samples to generate.
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel sampling (default is `true`).

        Returns
        -------
        GaussTable
            A new dataset containing the samples.
        """

    def estimate(
        self,
        x: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        seed: builtins.int = 31,
        parallel: builtins.bool = True,
    ) -> GaussCPD:
        r"""
        Estimate a conditional probability distribution (CPD).

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables.
        z: str | Iterable[str]
            A conditioning variable or an iterable of conditioning variables.
        w: GaussEv | dict[str, float] | None
            Optional evidence to condition on during inference.
        estimator: EstimatorMethod | None
            The estimator to use for estimation (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel estimation (default is `true`).

        Returns
        -------
        GaussCPD
            A new conditional probability distribution.
        """

    def do_estimate(
        self,
        x: typing.Any,
        y: typing.Any,
        z: typing.Any,
        w: typing.Optional[typing.Any] = None,
        estimator: typing.Optional[estimators.EstimatorMethod] = None,
        missing_method: typing.Optional[datasets.MissingMethod] = None,
        missing_mechanism: typing.Optional[datasets.MissingMechanism] = None,
        seed: builtins.int = 31,
        parallel: builtins.bool = True,
    ) -> typing.Optional[GaussCPD]:
        r"""
        Estimate a conditional population average causal effect (CPACE).

        Parameters
        ----------
        x: str | Iterable[str]
            An intervention variable or an iterable of intervention variables.
        y: str | Iterable[str]
            An outcome variable or an iterable of outcome variables.
        z: str | Iterable[str]
            A conditioning variable or an iterable of conditioning variables.
        w: GaussEv | dict[str, float] | None
            Optional evidence to condition on during inference.
        estimator: EstimatorMethod | None
            The estimator to use for estimation (default is `EstimatorMethod.BE`).
        missing_method: MissingMethod | None
            The method to use for handling missing data (default is `MissingMethod.PW`).
        missing_mechanism: MissingMechanism | None
            The missing mechanism to use for handling missing data (default is `None`).
        seed: int
            The seed of the random number generator (default is `31`).
        parallel: bool
            The flag to enable parallel estimation (default is `true`).

        Returns
        -------
        GaussCPD | None
            A new conditional population average causal effect (CPACE) distribution, if identifiable.
        """

    @classmethod
    def random(
        cls,
        labels: typing.Any,
        s_a: builtins.float = 1.0,
        s_b: builtins.float = 1.0,
        e: builtins.float = 1e-06,
        p: builtins.float = 0.1,
        seed: builtins.int = 31,
    ) -> GaussBN:
        r"""
        Generates a random Gaussian Bayesian network.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the variables.
        s_a: float, default=1.0
            The standard deviation of the regression coefficients.
        s_b: float, default=1.0
            The standard deviation of the intercept.
        e: float, default=1e-6
            A small positive constant for covariance regularization.
        p: float, default=0.1
            The probability of generating an edge.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        GaussBN
            A random Gaussian Bayesian network.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> GaussBN:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        GaussBN
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> GaussBN:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        GaussBN
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class GaussCPD:
    r"""
    A struct representing a Gaussian conditional probability distribution.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the label of the conditioned variable.

        Returns
        -------
        list[str]
            A reference to the label.
        """

    def conditioning_labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the conditioned variables.

        Returns
        -------
        list[str]
            A reference to the conditioning labels.
        """

    def support(
        self,
    ) -> builtins.dict[builtins.str, tuple[builtins.float, builtins.float]]:
        r"""
        Returns the support of each variable.

        Returns
        -------
        dict[str, tuple[float, float]]
            A map from variable names to (min, max) ranges.
        """

    def conditioning_support(
        self,
    ) -> builtins.dict[builtins.str, tuple[builtins.float, builtins.float]]:
        r"""
        Returns the support of the conditioning variables.

        Returns
        -------
        dict[str, tuple[float, float]]
            A map from conditioning variable names to (min, max) ranges.
        """

    def parameters(self) -> dict:
        r"""
        Returns the parameters.

        Returns
        -------
        dict[str, ...]
            A reference to the parameters.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.

        Returns
        -------
        int
            The parameters size.
        """

    def fitted_statistics(self) -> typing.Optional[dict]:
        r"""
        Returns the fitted statistics used to fit the distribution, if any.

        Returns
        -------
        dict[str, ...] | None
            A dictionary containing the fitted statistics used to fit the distribution, if any.
        """

    def fitted_log_likelihood(self) -> typing.Optional[builtins.float]:
        r"""
        Returns the log-likelihood given the distribution, if any.

        Returns
        -------
        float | None
            The log-likelihood given the distribution, if any.
        """

    @classmethod
    def random(
        cls,
        labels: typing.Any,
        conditioning_labels: typing.Any,
        s_a: builtins.float = 1.0,
        s_b: builtins.float = 1.0,
        e: builtins.float = 1e-06,
        seed: builtins.int = 31,
    ) -> GaussCPD:
        r"""
        Generates a random Gaussian conditional probability distribution.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the target variables.
        conditioning_labels: Iterable[str]
            The labels of the conditioning variables.
        s_a: float, default=1.0
            The standard deviation of the regression coefficients.
        s_b: float, default=1.0
            The standard deviation of the intercept.
        e: float, default=1e-6
            A small positive constant for covariance regularization.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        GaussCPD
            A random Gaussian conditional probability distribution.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> GaussCPD:
        r"""
        Read instance from a JSON string.

        Parameters
        ----------
        json: str
            The JSON string to read from.

        Returns
        -------
        GaussCPD
            A new instance.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.

        Returns
        -------
        str
            A JSON string representation of the instance.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> GaussCPD:
        r"""
        Read instance from a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to read from.

        Returns
        -------
        GaussCPD
            A new instance.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.

        Parameters
        ----------
        path: str
            The path to the JSON file to write to.
        """

@typing.final
class GaussPhi:
    r"""
    A struct representing a Gaussian potential (information form).
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the potential.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.
        """

    def condition(self, evidence: typing.Any) -> GaussPhi:
        r"""
        Conditions the potential on observed evidence.
        """

    def marginalize(self, x: typing.Any) -> GaussPhi:
        r"""
        Marginalizes the potential over a set of variables.
        """

    def normalize(self) -> GaussPhi:
        r"""
        Normalizes the potential.
        """

    def precision_matrix(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Returns the precision matrix of the potential.
        """

    def information_vector(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Returns the information vector of the potential.
        """

    def log_normalization_constant(self) -> builtins.float:
        r"""
        Returns the log normalization constant of the potential.
        """

    @classmethod
    def from_cpd(cls, cpd: GaussCPD) -> GaussPhi:
        r"""
        Converts a GaussCPD to a GaussPhi.
        """

    def into_cpd(self, x: typing.Any, z: typing.Any) -> GaussCPD:
        r"""
        Converts the potential to a GaussCPD.
        """

    def __repr__(self) -> builtins.str:
        r"""
        Returns the string representation of the GaussPhi.
        """

    def __mul__(self, other: GaussPhi) -> GaussPhi:
        r"""
        Multiplies two potentials.
        """

    def __imul__(self, other: GaussPhi) -> None:
        r"""
        In-place multiplication of two potentials.
        """

    def __truediv__(self, other: GaussPhi) -> GaussPhi:
        r"""
        Divides two potentials.
        """

    def __idiv__(self, other: GaussPhi) -> None:
        r"""
        In-place division of two potentials.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> GaussPhi:
        r"""
        Read instance from a JSON string.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> GaussPhi:
        r"""
        Read instance from a JSON file.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.
        """

@typing.final
class MixedBN:
    r"""
    A mixed Bayesian network.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, graph: DiGraph, cpds: typing.Any) -> MixedBN:
        r"""
        Constructs a new mixed Bayesian network.
        """

    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the name of the model, if any.
        """

    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the description of the model, if any.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the variables.
        """

    def graph(self) -> DiGraph:
        r"""
        Returns the underlying graph.
        """

    def cpds(self) -> builtins.dict[builtins.str, MixedCPD]:
        r"""
        Returns a map of labels to CPDs.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.
        """

    def select(self, x: typing.Any) -> MixedBN:
        r"""
        Restrict the model to the specified variables.

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables to select.

        Returns
        -------
        MixedBN
            A model restricted to the specified variables.
        """

    def topological_order(self) -> builtins.list[builtins.str]:
        r"""
        Returns the topological order of the underlying graph.

        Returns
        -------
        list[str]
            A topological ordering of the variables.
        """

    def sample(
        self, n: builtins.int, seed: builtins.int = 31, parallel: builtins.bool = True
    ) -> datasets.MixedTable:
        r"""
        Generate samples from the model.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> MixedBN:
        r"""
        Read instance from a JSON string.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> MixedBN:
        r"""
        Read instance from a JSON file.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.
        """

@typing.final
class MixedCPD:
    r"""
    A unified CPD type for mixed Bayesian networks.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def is_categorical(self) -> builtins.bool:
        r"""
        Returns true if the CPD is categorical.
        """

    def is_gaussian(self) -> builtins.bool:
        r"""
        Returns true if the CPD is gaussian.
        """

    def as_catcpd(self) -> typing.Optional[CatCPD]:
        r"""
        Returns the inner CatCPD if the CPD is categorical.
        """

    def as_gausscpd(self) -> typing.Optional[GaussCPD]:
        r"""
        Returns the inner GaussCPD if the CPD is gaussian.
        """

    @classmethod
    def from_catcpd(cls, cpd: CatCPD) -> MixedCPD:
        r"""
        Creates a MixedCPD from a CatCPD.
        """

    @classmethod
    def from_gausscpd(cls, cpd: GaussCPD) -> MixedCPD:
        r"""
        Creates a MixedCPD from a GaussCPD.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the CPD.
        """

    def conditioning_labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the conditioning labels of the CPD.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.
        """

    def __repr__(self) -> builtins.str:
        r"""
        Returns the string representation of the MixedCPD.
        """

@typing.final
class MixedPhi:
    r"""
    A unified potential for mixed Bayesian networks.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def is_categorical(self) -> builtins.bool:
        r"""
        Returns true if the potential is categorical.
        """

    def is_gaussian(self) -> builtins.bool:
        r"""
        Returns true if the potential is Gaussian.
        """

    def as_catphi(self) -> typing.Optional[CatPhi]:
        r"""
        Returns the inner CatPhi if the potential is categorical.
        """

    def as_gaussphi(self) -> typing.Optional[GaussPhi]:
        r"""
        Returns the inner GaussPhi if the potential is Gaussian.
        """

    def labels(self) -> builtins.list[builtins.str]:
        r"""
        Returns the labels of the potential.
        """

    def parameters_size(self) -> builtins.int:
        r"""
        Returns the parameters size.
        """

    def condition(self, evidence: typing.Any) -> MixedPhi:
        r"""
        Conditions the potential on observed evidence.
        """

    def marginalize(self, x: typing.Any) -> MixedPhi:
        r"""
        Marginalizes the potential over a set of variables.
        """

    def normalize(self) -> MixedPhi:
        r"""
        Normalizes the potential.
        """

    @classmethod
    def from_cat_cpd(cls, cpd: CatCPD) -> MixedPhi:
        r"""
        Creates a MixedPhi from a CatCPD.
        """

    @classmethod
    def from_gauss_cpd(cls, cpd: GaussCPD) -> MixedPhi:
        r"""
        Creates a MixedPhi from a GaussCPD.
        """

    def into_cat_cpd(self, x: typing.Any, z: typing.Any) -> CatCPD:
        r"""
        Converts to a CatCPD if the potential is categorical.
        """

    def into_gauss_cpd(self, x: typing.Any, z: typing.Any) -> GaussCPD:
        r"""
        Converts to a GaussCPD if the potential is Gaussian.
        """

    def __repr__(self) -> builtins.str:
        r"""
        Returns the string representation of the MixedPhi.
        """

    def __mul__(self, other: MixedPhi) -> MixedPhi:
        r"""
        Multiplies two potentials.
        """

    def __imul__(self, other: MixedPhi) -> None:
        r"""
        In-place multiplication of two potentials.
        """

    def __truediv__(self, other: MixedPhi) -> MixedPhi:
        r"""
        Divides two potentials.
        """

    def __idiv__(self, other: MixedPhi) -> None:
        r"""
        In-place division of two potentials.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> MixedPhi:
        r"""
        Read instance from a JSON string.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> MixedPhi:
        r"""
        Read instance from a JSON file.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.
        """

@typing.final
class UnGraph:
    r"""
    A struct representing an undirected graph using an adjacency matrix.
    """

    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    @classmethod
    def empty(cls, vertices: typing.Any) -> UnGraph:
        r"""
        Creates an empty undirected graph with the given vertices.

        Parameters
        ----------
        vertices: Iterable[str]
            The vertices of the graph.
            Vertices will be sorted in alphabetical order.

        Returns
        -------
        UnGraph
            A new graph instance.
        """

    @classmethod
    def complete(cls, vertices: typing.Any) -> UnGraph:
        r"""
        Creates a complete undirected graph with the given vertices.

        Parameters
        ----------
        vertices: Iterable[str]
            The vertices of the graph.
            Vertices will be sorted in alphabetical order.
            No self-loops are created.

        Returns
        -------
        UnGraph
            A new graph instance.
        """

    def vertices(self) -> builtins.list[builtins.str]:
        r"""
        Returns the vertices of the graph.

        Returns
        -------
        list[str]
            A list of vertices.
        """

    def has_vertex(self, x: builtins.str) -> builtins.bool:
        r"""
        Checks if a vertex exists in the graph.

        Parameters
        ----------
        x: str
            The vertex.

        Returns
        -------
        bool
            `true` if the vertex exists, `false` otherwise.
        """

    def add_vertex(self, x: builtins.str) -> builtins.int:
        r"""
        Adds a new vertex with the given label to the graph.

        Parameters
        ----------
        x: str
            The label of the vertex to add.

        Returns
        -------
        int
            The index of the (possibly new) vertex.
            Vertices are kept sorted in alphabetical order:
            adding a vertex may shift the indices of other vertices.
        """

    def del_vertex(self, x: builtins.str) -> builtins.bool:
        r"""
        Deletes the vertex with the given label from the graph,
        together with all its incident edges.

        Parameters
        ----------
        x: str
            The label of the vertex to delete.

        Returns
        -------
        bool
            `true` if the vertex was deleted, `false` if it did not exist.
            Vertices are kept sorted in alphabetical order:
            deleting a vertex may shift the indices of other vertices.
        """

    def edges(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        Returns the edges of the graph.

        Returns
        -------
        list[tuple[str, str]]
            A list of edges.
        """

    def has_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Checks if there is an edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if there is an edge between `x` and `y`, `false` otherwise.
        """

    def add_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Adds an edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if the edge was added, `false` if it already existed.
        """

    def del_edge(self, x: builtins.str, y: builtins.str) -> builtins.bool:
        r"""
        Deletes the edge between vertices `x` and `y`.

        Parameters
        ----------
        x: str
            The first vertex.
        y: str
            The second vertex.

        Returns
        -------
        bool
            `true` if the edge was deleted, `false` if it did not exist.
        """

    def neighbors(self, x: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Returns the neighbors of a vertex `x`.

        Parameters
        ----------
        x: str | Iterable[str]
            A vertex or an iterable of vertices.

        Returns
        -------
        list[str]
            A list of neighbor vertices.
        """

    def select(self, x: typing.Any) -> UnGraph:
        r"""
        Restrict the graph to the specified variables.

        Parameters
        ----------
        x: str | Iterable[str]
            A variable or an iterable of variables to select.

        Returns
        -------
        UnGraph
            A graph restricted to the specified variables.
        """

    @classmethod
    def from_adjacency_matrix(
        cls, labels: typing.Any, adjacency_matrix: typing.Any
    ) -> UnGraph:
        r"""
        Creates an undirected graph from an adjacency matrix and labels.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the vertices.
        adjacency_matrix: numpy.ndarray
            A 2D boolean array representing the (symmetric) adjacency matrix.

        Returns
        -------
        UnGraph
            A new graph instance.
        """

    def to_adjacency_matrix(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Converts the graph to an adjacency matrix.

        Returns
        -------
        numpy.ndarray
            A 2D boolean array representing the adjacency matrix.
        """

    @classmethod
    def random(
        cls, labels: typing.Any, p: builtins.float = 0.1, seed: builtins.int = 31
    ) -> UnGraph:
        r"""
        Generates a random undirected graph.

        Parameters
        ----------
        labels: Iterable[str]
            The labels of the graph.
        p: float, default=0.1
            The probability of generating an edge.
        seed: int, default=31
            The seed for the random number generator.

        Returns
        -------
        UnGraph
            A random undirected graph.
        """

    @classmethod
    def from_json_string(cls, json: builtins.str) -> UnGraph:
        r"""
        Read instance from a JSON string.
        """

    def to_json_string(self) -> builtins.str:
        r"""
        Write instance to a JSON string.
        """

    @classmethod
    def from_json_file(cls, path: builtins.str) -> UnGraph:
        r"""
        Read instance from a JSON file.
        """

    def to_json_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a JSON file.
        """

    @classmethod
    def from_dot_string(cls, dot: builtins.str) -> UnGraph:
        r"""
        Read instance from a DOT string.
        """

    def to_dot_string(self) -> builtins.str:
        r"""
        Write instance to a DOT string.
        """

    @classmethod
    def from_dot_file(cls, path: builtins.str) -> UnGraph:
        r"""
        Read instance from a DOT file.
        """

    def to_dot_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a DOT file.
        """

    @classmethod
    def from_gml_string(cls, gml: builtins.str) -> UnGraph:
        r"""
        Read instance from a GML string.
        """

    def to_gml_string(self) -> builtins.str:
        r"""
        Write instance to a GML string.
        """

    @classmethod
    def from_gml_file(cls, path: builtins.str) -> UnGraph:
        r"""
        Read instance from a GML file.
        """

    def to_gml_file(self, path: builtins.str) -> None:
        r"""
        Write instance to a GML file.
        """
