# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import causal_hub.models

__all__ = [
    "load_alarm",
    "load_andes",
    "load_arth150",
    "load_asia",
    "load_barley",
    "load_cancer",
    "load_child",
    "load_diabetes",
    "load_earthquake",
    "load_eating",
    "load_ecoli70",
    "load_hailfinder",
    "load_hepar2",
    "load_insurance",
    "load_link",
    "load_magic_irri",
    "load_magic_niab",
    "load_mildew",
    "load_munin1",
    "load_pathfinder",
    "load_pigs",
    "load_sachs",
    "load_survey",
    "load_water",
    "load_win95pts",
]

def load_alarm() -> models.CatBN:
    r"""
    Load the `ALARM` categorical BN from the assets.
    """

def load_andes() -> models.CatBN:
    r"""
    Load the `ANDES` categorical BN from the assets.
    """

def load_arth150() -> models.GaussBN:
    r"""
    Load the `ARTH150` Gaussian BN from the assets.
    """

def load_asia() -> models.CatBN:
    r"""
    Load the `ASIA` categorical BN from the assets.
    """

def load_barley() -> models.CatBN:
    r"""
    Load the `BARLEY` categorical BN from the assets.
    """

def load_cancer() -> models.CatBN:
    r"""
    Load the `CANCER` categorical BN from the assets.
    """

def load_child() -> models.CatBN:
    r"""
    Load the `CHILD` categorical BN from the assets.
    """

def load_diabetes() -> models.CatBN:
    r"""
    Load the `DIABETES` categorical BN from the assets.
    """

def load_earthquake() -> models.CatBN:
    r"""
    Load the `EARTHQUAKE` categorical BN from the assets.
    """

def load_eating() -> models.CatCTBN:
    r"""
    Load the `EATING` categorical CTBN from the assets.
    """

def load_ecoli70() -> models.GaussBN:
    r"""
    Load the `ECOLI70` Gaussian BN from the assets.
    """

def load_hailfinder() -> models.CatBN:
    r"""
    Load the `HAILFINDER` categorical BN from the assets.
    """

def load_hepar2() -> models.CatBN:
    r"""
    Load the `HEPAR2` categorical BN from the assets.
    """

def load_insurance() -> models.CatBN:
    r"""
    Load the `INSURANCE` categorical BN from the assets.
    """

def load_link() -> models.CatBN:
    r"""
    Load the `LINK` categorical BN from the assets.
    """

def load_magic_irri() -> models.GaussBN:
    r"""
    Load the `MAGIC_IRRI` Gaussian BN from the assets.
    """

def load_magic_niab() -> models.GaussBN:
    r"""
    Load the `MAGIC_NIAB` Gaussian BN from the assets.
    """

def load_mildew() -> models.CatBN:
    r"""
    Load the `MILDEW` categorical BN from the assets.
    """

def load_munin1() -> models.CatBN:
    r"""
    Load the `MUNIN1` categorical BN from the assets.
    """

def load_pathfinder() -> models.CatBN:
    r"""
    Load the `PATHFINDER` categorical BN from the assets.
    """

def load_pigs() -> models.CatBN:
    r"""
    Load the `PIGS` categorical BN from the assets.
    """

def load_sachs() -> models.CatBN:
    r"""
    Load the `SACHS` categorical BN from the assets.
    """

def load_survey() -> models.CatBN:
    r"""
    Load the `SURVEY` categorical BN from the assets.
    """

def load_water() -> models.CatBN:
    r"""
    Load the `WATER` categorical BN from the assets.
    """

def load_win95pts() -> models.CatBN:
    r"""
    Load the `WIN95PTS` categorical BN from the assets.
    """
