on: [push, pull_request]

name: build

jobs:
  build:
    name: causal-hub
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # FIXME: , windows-latest]
        env: ["stable", "beta", "nightly"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
            vcpkg
          key: ${{ runner.os }}-rust-${{ matrix.env }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('.github/workflows/build.yml') }}
      - name: Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.env }}
      - name: Dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            graphviz
      - name: Dependencies (MacOS)
        if: ${{ runner.os == 'MacOS' }}
        run: |
          brew install openblas
          brew install graphviz
      - name: Dependencies (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "FIXME: Fix LAPACK build in VCPKG"
      - name: Build
        run: cargo +${{ matrix.env }} build -v
      - name: Test
        run: |
          unzip -o ./tests/assets -d ./tests
          cargo +${{ matrix.env }} test --tests -v
      - name: Publish
        if: ${{ runner.os == 'Linux' && matrix.env == 'stable' && github.ref == 'refs/heads/main' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login "$CARGO_REGISTRY_TOKEN"
          cargo publish --allow-dirty
      - name: 'Artifacts'
        uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Linux' && matrix.env == 'stable' && github.ref == 'refs/heads/main' }}
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
