on: [push, pull_request]

name: coverage

jobs:
  build:
    name: causal-hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: target
          key: Linux-rust-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('.github/workflows/coverage.yml') }}
      - name: Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            graphviz
      - name: Coverage
        run: |
          unzip -o ./tests/assets -d ./tests
          cargo install cargo-llvm-cov
          cargo llvm-cov --lcov --output-path lcov.info -v
      - name: CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: unittests
          fail_ci_if_error: true
