on: [push, pull_request]

name: docoverage

jobs:
  build:
    name: causal-hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: target
          key: Linux-rust-nightly-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('.github/workflows/docoverage.yml') }}
      - name: Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Docs Coverage
        run: cargo +nightly rustdoc -- --show-coverage -Z unstable-options
