on: [push, pull_request]

name: doctest

jobs:
  build:
    name: causal-hub
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # FIXME: , macos-latest, windows-latest]
        env: ["stable", "beta", "nightly"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ matrix.env }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('.github/workflows/doctest.yml') }}
      - name: Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.env }}
      - name: Dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            graphviz
      - name: Dependencies (MacOS)
        if: ${{ runner.os == 'MacOS' }}
        run: |
          brew install openblas
          brew install graphviz
      - name: Dependencies (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "FIXME: Fix LAPACK build in VCPKG"
      - name: Doctest
        run: cargo +${{ matrix.env }} test --doc -v
