on: [push, pull_request]

name: doctest

jobs:
  build:
    name: causal-hub
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        # NOTE: rustdoc link each doctest separately. On GitHub,
        # MacOS runners have three cores, while Ubuntu and Windows
        # have two cores. To decrease workflow times (due to `polars`),
        # we run doctests on MacOS only, while unit/integration test
        # run on every platform and every compiler channel.
        os: [macos-latest] # [ubuntu-latest, macos-latest, windows-latest]
        env: ["stable", "beta", "nightly"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ matrix.env }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('.github/workflows/doctest.yml') }}
      - name: Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.env }}
      - name: Doctest
        run: cargo +${{ matrix.env }} test --doc -v
